### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by gmitch215** [CodeMC/Bot#6]
Set up a PR to add GitHub Action workflow that sets up a testing environment for the bot.

I found a [Unit Testing Framework](https://github.com/ColyTeam/JDATesting) for JDA that's currently maintained and could be used. Would also replicate the Jenkins/Nexus containers in the API repository for testing against similar instances.

**Comment by Andre601** [comment]
Is this issue still relevant?

**Comment by gmitch215** [comment]
It is, but is still very low-priority. I'll submit a PR in the next few days once we can confirm that most of the existing issues with the bot are solved.
